#!/usr/bin/env python3

"""
Reorders a tab-delimited file based on row numbers extracted from a gene list file.

This script is for tab files generated by computeMatrix,
which have three header lines. File 1 should contain gene names and their corresponding
row numbers in the second column. These row numbers indicate the
original positions in a BED file.

The script:
1. Extracts row numbers from File 1.
2. Adjusts row numbers to account for the extra headers in the computeMatrix tab file.
3. Reads the tab file and builds a mapping of row numbers to data lines.
4. Reorders the data lines based on the adjusted row numbers from File 1.
5. Writes the three original header lines followed by the reordered data to the output file.
"""

def run(file1, tabfile, output):
    """
    Parameters:
        file1   : Path to gene list file with row numbers        sample ex: mapped_rows.txt
        tabfile : Path to tab-delimited file to reorder          sample ex: rownum_tab.tab 
        output  : Path to save reordered tab file                sample ex: reordered_tab.tab
        
    """

    # Reading File 1 and extract row numbers
    row_numbers = []
    with open(file1) as f:
        for line in f:
            if not line.strip():
                continue
            parts = line.strip().split("\t")
            if len(parts) > 1:
                row_nums = parts[1].split(",")
                row_numbers.extend([int(num.strip()) for num in row_nums])

    # Adjust row numbers due to headers (+2), tab file has 3 headers, BED has 1
    adjusted_row_numbers = [num + 2 for num in row_numbers]

    # Reading tab file and build dictionary of row numbers to lines
    row_dict = {}
    with open(tabfile) as f:
        header_lines = [next(f) for _ in range(3)]  # first 3 header lines
        for line in f:
            columns = line.strip().split("\t")
            row_number_in_file = int(columns[-1])
            row_dict[row_number_in_file] = line

    # Reordering the data based on adjusted row numbers
    reordered_data = []
    for adjusted_row_number in adjusted_row_numbers:
        if adjusted_row_number in row_dict:
            reordered_data.append(row_dict[adjusted_row_number])

    # Writing reordered data to output file
    with open(output, 'w') as out:
        out.writelines(header_lines)
        out.writelines(reordered_data)

    print(f"[reordering_tab] Reordered tab file saved: {output}")
